"""Pydantic configuration for the native asyncssh lure subsystem.

Re-exported through :mod:`anglerfish.config.models` so existing
import paths keep working. Lives here so lure-specific validation and
defaults stay next to the code that consumes them.

The runtime bait-NIC presence check is intentionally not in the
Pydantic validator: config may be built on a different host than the
one the lure runs on (ISO bake, configuration management). The
validator catches obvious mistakes (range, port collision, IP
format); the runtime check lives in :class:`LureServer.start` and
reads the live interface list at boot.
"""

from __future__ import annotations

import ipaddress
from pathlib import Path
from typing import Self

from pydantic import BaseModel, ConfigDict, Field, HttpUrl, IPvAnyAddress, model_validator

__all__ = ["LureConfig"]


class LureConfig(BaseModel):
    """Settings for the native SSH (and future HTTP) lure listeners."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    # Whether the lure starts at all. Anglerfish AI is a honeypot
    # product: the listener is the point. Default on, opt-out via
    # ANGLERFISH_LURE__ENABLED=false for operators who want the bridge
    # and dashboard up but the SSH listener disabled (development,
    # offline analysis, staged rollouts). Stage 2A ships the config
    # ahead of the runtime; the `lure serve` CLI lands in Stage 2B and
    # handles the case where the runtime is not yet installed.
    enabled: bool = Field(
        default=True,
        description=(
            "Whether the SSH lure listener binds at startup. Default "
            "True: the honeypot listener is the product. Set False to "
            "run bridge + dashboard without exposing the SSH listener."
        ),
    )

    # Network
    listen_host: IPvAnyAddress = Field(
        default=ipaddress.IPv4Address("0.0.0.0"),  # noqa: S104 - intentionally wildcard
        description=(
            "Bait-NIC IP to bind the SSH listener on. The lure refuses "
            "to start unless this IP is currently assigned to an "
            "interface on the host (checked at runtime by LureServer). "
            "Default 0.0.0.0 is intentionally the unspecified address "
            "so a missing config fails the bait-NIC sanity check rather "
            "than silently binding to every interface."
        ),
    )
    listen_port: int = Field(
        default=2222,
        ge=0,
        le=65535,
        description=(
            "TCP port the SSH listener binds to. 0 means kernel-assigned "
            "ephemeral; useful for tests and for sysadmins that pin the "
            "actual port via systemd socket activation. In production use "
            "22 (with CAP_NET_BIND_SERVICE) or 2222."
        ),
    )

    # Identity
    hostname: str = Field(default="srv-prod-01", min_length=1, max_length=63)
    banner_openssh_version: str = Field(default="9.2p1", min_length=1, max_length=64)
    banner_debian_version: str = Field(default="2+deb12u3", min_length=1, max_length=64)

    # Host keys (generated by the wizard, loaded by the lure at startup)
    host_key_dir: Path = Field(
        default=Path("/var/lib/anglerfish/lure-keys"),
        description=(
            "Directory storing the lure's RSA-4096 and Ed25519 host "
            "keys. Generated at first boot via the wizard; never "
            "lives in the repo. Mode 0700 on the dir and 0600 on the "
            "key files is enforced at startup."
        ),
    )

    # Input sanitisation. Smaller cap than BridgeConfig.max_input_chars
    # because lure caps closer to the attacker; the bridge re-sanitises
    # on top so the defense scan window is never the binding constraint.
    max_command_chars: int = Field(default=1024, gt=0, le=8192)

    # Session state
    history_window: int = Field(
        default=200,
        ge=1,
        le=2000,
        description="Per-session command history depth kept for `history` builtin and audit.",
    )

    # Per-source-IP rate limit. 3 concurrent stops one IP from hogging
    # every slot. 30 per minute leaves room for burst brute force tools
    # to deliver their full credential payload before throttle.
    per_ip_max_concurrent_connections: int = Field(default=3, ge=1, le=100)
    per_ip_max_connections_per_minute: int = Field(default=30, ge=1, le=600)

    # Bridge link (the lure speaks to the bridge HTTP API)
    bridge_base_url: HttpUrl = Field(default=HttpUrl("http://127.0.0.1:8421/"))
    bridge_request_timeout_s: float = Field(default=30.0, gt=0.0, le=120.0)
    bridge_connect_timeout_s: float = Field(default=2.0, gt=0.0, le=30.0)
    bridge_stream_enabled: bool = Field(
        default=True,
        description=(
            "When True, the lure uses protocol v3 ?stream=1 against the "
            "bridge command endpoint so attacker terminals see output "
            "appear progressively rather than as one buffered chunk. "
            "Disable to revert to v2 buffered semantics; useful when "
            "running a v3 lure against a v2-only rolled-back bridge "
            "(the bridge would 422 on the unknown ?stream= query)."
        ),
    )

    # Native-command timing-jitter defence so native vs bridge response
    # latency is not an attacker fingerprint. See
    # docs/design/STAGE_2_lure_subsystem.md "Native-command timing
    # jitter" for the full rationale.
    timing_jitter_enabled: bool = Field(default=True)
    timing_jitter_floor_ms: int = Field(default=200, ge=0, le=5000)
    timing_jitter_ceiling_ms: int = Field(default=3500, ge=100, le=10000)
    timing_jitter_bootstrap_min_ms: int = Field(default=800, ge=0, le=5000)
    timing_jitter_bootstrap_max_ms: int = Field(default=1800, ge=100, le=10000)

    # SSH liveness (RFC 4254). 60s / 3 mirrors OpenSSH defaults.
    keepalive_interval_s: int = Field(
        default=60,
        ge=0,
        le=3600,
        description="0 disables keepalives.",
    )
    keepalive_count_max: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Disconnect after N consecutive missed keepalives.",
    )

    # Future HTTP/HTTPS lure (TODO-1 in docs/TODO.md, stub at lure/http.py)
    http_lure_enabled: bool = Field(default=False)
    http_lure_listen_port: int = Field(default=8080, ge=1, le=65535)

    @model_validator(mode="after")
    def _ports_must_differ(self) -> Self:
        if self.http_lure_enabled and self.http_lure_listen_port == self.listen_port:
            raise ValueError(
                "lure.http_lure_listen_port must differ from lure.listen_port",
            )
        return self

    @model_validator(mode="after")
    def _jitter_bounds_consistent(self) -> Self:
        if self.timing_jitter_floor_ms > self.timing_jitter_ceiling_ms:
            raise ValueError(
                f"lure.timing_jitter_floor_ms ({self.timing_jitter_floor_ms}) must be "
                f"<= lure.timing_jitter_ceiling_ms ({self.timing_jitter_ceiling_ms})",
            )
        if self.timing_jitter_bootstrap_min_ms > self.timing_jitter_bootstrap_max_ms:
            raise ValueError(
                "lure.timing_jitter_bootstrap_min_ms must be <= "
                "lure.timing_jitter_bootstrap_max_ms",
            )
        return self
