"""Static in-process filesystem the lure serves natively.

About 50 paths covering the standard recon targets a botnet hits in
the first minutes of a Linux foothold: system identity, system config,
kernel/hardware, user homes, common logs, top-level listings. Anything
outside this table routes to the bridge.

The set is intentionally curated for the *known* attacker-cat paths
(sudoers, crontab, passwd, shadow, ssh configs, recent log lines) so
the LLM never needs to invent file contents that would contradict
what the lure already serves.

Content is identical across sessions and across the lifetime of the
lure process: the design (see ``docs/design/STAGE_2_lure_subsystem.md``
"Static fake filesystem") deliberately rejects per-session randomness
for v1 to bound complexity and avoid contradictions between bridge-
served and lure-served output.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Final, Literal

from anglerfish.lure.session import LureSessionContext

__all__ = [
    "FakeEntry",
    "ListResult",
    "ReadResult",
    "listdir",
    "read",
    "system_prompt_summary",
]


@dataclass(frozen=True)
class FakeEntry:
    """One filesystem entry as ``ls -l`` would render it."""

    name: str
    mode: int
    size: int
    owner: str = "root"
    group: str = "root"
    mtime: int = 1715000000  # frozen per session, plausible recent epoch
    is_dir: bool = False
    is_symlink: bool = False
    target: str | None = None


@dataclass(frozen=True)
class ReadResult:
    """Outcome of a :func:`read` call."""

    status: Literal["content", "permission_denied", "not_in_fakefs"]
    content: str = ""


@dataclass(frozen=True)
class ListResult:
    """Outcome of a :func:`listdir` call."""

    status: Literal["entries", "not_in_fakefs"]
    entries: tuple[FakeEntry, ...] = field(default_factory=tuple)


# Mode helpers for readability inside _DIRS.
_F664 = 0o100664
_F644 = 0o100644
_F640 = 0o100640
_F600 = 0o100600
_F755 = 0o100755
_F444 = 0o100444
_D755 = 0o040755
_D700 = 0o040700
_L777 = 0o120777  # symlink


# ---------------------------------------------------------------------------
# Static file contents (path -> str). User-specific entries get formatted
# with session.username at read time; placeholders below use {user}.
# ---------------------------------------------------------------------------

_ETC_PASSWD = """\
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
systemd-resolve:x:101:103:systemd Resolver,,,:/run/systemd:/usr/sbin/nologin
sshd:x:102:65534::/run/sshd:/usr/sbin/nologin
{user}:x:1000:1000:{user},,,:/home/{user}:/bin/bash
"""

_ETC_GROUP = """\
root:x:0:
daemon:x:1:
bin:x:2:
sys:x:3:
mail:x:8:
shadow:x:42:
www-data:x:33:
nobody:x:65534:
ssh:x:107:
sudo:x:27:{user}
{user}:x:1000:
"""

_ETC_ISSUE = "Debian GNU/Linux 12 \\n \\l\n"

_ETC_OS_RELEASE = """\
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
"""

_ETC_HOSTS = """\
127.0.0.1 localhost
::1       localhost ip6-localhost ip6-loopback
ff02::1   ip6-allnodes
ff02::2   ip6-allrouters
"""

_ETC_RESOLV_CONF = """\
# Generated by NetworkManager
nameserver 127.0.0.53
options edns0 trust-ad
search .
"""

_ETC_NSSWITCH = """\
passwd:         files systemd
group:          files systemd
shadow:         files
hosts:          files mdns4_minimal [NOTFOUND=return] dns
networks:       files
protocols:      db files
services:       db files
ethers:         db files
rpc:            db files
netgroup:       nis
"""

_ETC_FSTAB = """\
# /etc/fstab: static file system information.
UUID=4cef1f6e-2e1e-4f7b-9a0d-2c7c9a6f1abc / ext4 errors=remount-ro 0 1
UUID=1e3a-7fb9 /boot/efi vfat umask=0077 0 1
/swap.img none swap sw 0 0
"""

_ETC_CRONTAB = """\
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

17 *  * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6  * * *   root    test -x /usr/sbin/anacron || (cd / && run-parts --report /etc/cron.daily)
47 6  * * 7   root    test -x /usr/sbin/anacron || (cd / && run-parts --report /etc/cron.weekly)
52 6  1 * *   root    test -x /usr/sbin/anacron || (cd / && run-parts --report /etc/cron.monthly)
"""

_ETC_PROFILE = """\
if [ "${PS1-}" ]; then
  if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    PS1='$ '
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
"""

_ETC_BASH_BASHRC = """\
# System-wide .bashrc file for interactive bash(1) shells.
[ -z "$PS1" ] && return
shopt -s checkwinsize
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
"""

_ETC_SSH_SSHD_CONFIG = """\
# Debian default sshd_config (excerpt)
Include /etc/ssh/sshd_config.d/*.conf
PermitRootLogin prohibit-password
PasswordAuthentication yes
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
"""

_ETC_SSH_SSH_CONFIG = """\
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
"""

_ETC_APT_SOURCES = """\
deb http://deb.debian.org/debian bookworm main contrib non-free-firmware
deb http://deb.debian.org/debian bookworm-updates main contrib non-free-firmware
deb http://security.debian.org/debian-security bookworm-security main contrib non-free-firmware
"""

_ETC_NETWORK_INTERFACES = """\
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback
"""

_PROC_VERSION = (
    "Linux version 6.1.0-18-amd64 (debian-kernel@lists.debian.org) "
    "(gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) "
    "#1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01)\n"
)

_PROC_CPUINFO = """\
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
stepping        : 1
microcode       : 0xb000040
cpu MHz         : 2399.998
cache size      : 35840 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
"""

_PROC_MEMINFO = """\
MemTotal:        8071672 kB
MemFree:         6128944 kB
MemAvailable:    7234128 kB
Buffers:           96384 kB
Cached:          1162152 kB
SwapTotal:       2097148 kB
SwapFree:        2097148 kB
"""

_PROC_MOUNTS = """\
/dev/vda1 / ext4 rw,relatime,errors=remount-ro 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sys /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /run tmpfs rw,nosuid,nodev,size=807168k,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /tmp tmpfs rw,nosuid,nodev,relatime 0 0
"""

_PROC_LOADAVG = "0.04 0.11 0.07 1/142 1432\n"

_PROC_UPTIME = "1234567.89 9876543.21\n"

_PROC_SELF_STATUS = """\
Name:   bash
Umask:  0022
State:  S (sleeping)
Tgid:   1432
Pid:    1432
PPid:   1431
Uid:    1000    1000    1000    1000
"""

_HOME_BASHRC = """\
# ~/.bashrc: executed by bash(1) for non-login shells.
case $- in *i*) ;; *) return;; esac
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s checkwinsize
"""

_HOME_PROFILE = """\
# ~/.profile: executed by the command interpreter for login shells.
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
"""

_ROOT_BASHRC = """\
# ~/.bashrc: executed by bash(1) for non-login shells.
PS1='\\u@\\h:\\w# '
alias ls='ls --color=auto'
"""

_ROOT_BASH_HISTORY = """\
ls -la
df -h
free -m
uname -a
ps aux
netstat -tunlp
systemctl status sshd
journalctl -u sshd -n 50
apt update
apt list --upgradable
top -bn1
who
last -n 20
crontab -l
cat /etc/passwd
cat /etc/shadow
docker ps
mount
ip a
exit
"""

_HOME_AUTHORIZED_KEYS_TEMPLATE = (
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIInpQwAGFNF1kF5HwTcQp1qP7vL1lP9z9XsRb6xY6r0L "
    "{user}@srv-prod-01\n"
)

_ROOT_AUTHORIZED_KEYS = (
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQ4xRRZ2XtFEABm1KvDr...truncated... root@bastion\n"
)

_HOME_KNOWN_HOSTS = """\
|1|abc=|def= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI...
|1|ghi=|jkl= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB...
|1|mno=|pqr= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlz...
"""

_VAR_LOG_AUTH = """\
May 23 14:01:03 srv-prod-01 sshd[1431]: Accepted publickey for {user} from 10.0.0.42 port 51221 ssh2: ED25519
May 23 14:01:03 srv-prod-01 sshd[1431]: pam_unix(sshd:session): session opened for user {user}
May 23 14:01:14 srv-prod-01 sudo:    {user} : TTY=pts/0 ; PWD=/home/{user} ; USER=root ; COMMAND=/usr/bin/apt update
May 23 14:01:14 srv-prod-01 sudo: pam_unix(sudo:session): session opened for user root
May 23 14:01:16 srv-prod-01 sudo: pam_unix(sudo:session): session closed for user root
May 23 14:02:01 srv-prod-01 CRON[1502]: pam_unix(cron:session): session opened for user root
May 23 14:02:01 srv-prod-01 CRON[1502]: pam_unix(cron:session): session closed for user root
May 23 14:05:33 srv-prod-01 sshd[1431]: pam_unix(sshd:session): session closed for user {user}
May 23 14:10:12 srv-prod-01 sshd[1601]: Failed password for invalid user admin from 198.51.100.7 port 38221 ssh2
May 23 14:10:14 srv-prod-01 sshd[1601]: Disconnected from invalid user admin 198.51.100.7 port 38221 [preauth]
"""

_VAR_LOG_SYSLOG = """\
May 23 14:01:01 srv-prod-01 systemd[1]: Starting Daily apt download activities...
May 23 14:01:02 srv-prod-01 systemd[1]: Finished Daily apt download activities.
May 23 14:02:01 srv-prod-01 CRON[1502]: (root) CMD (test -e /run/systemd/system || SERVICE_MODE=1 /usr/lib/x86_64-linux-gnu/e2fsprogs/e2scrub_all_cron)
May 23 14:02:55 srv-prod-01 kernel: [12345.678] EXT4-fs (vda1): re-mounted. Opts: errors=remount-ro
May 23 14:05:00 srv-prod-01 systemd[1]: Started Cleanup of Temporary Directories.
May 23 14:05:00 srv-prod-01 systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
May 23 14:10:00 srv-prod-01 systemd[1]: Started Daily cleanup of password and group caches.
May 23 14:11:23 srv-prod-01 dbus-daemon[687]: [system] Activating service name='org.freedesktop.timedate1'
May 23 14:15:42 srv-prod-01 kernel: [12389.123] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
May 23 14:20:00 srv-prod-01 systemd[1]: Started Time & Date Service.
"""

_VAR_LOG_DPKG = """\
2026-05-22 09:11:23 startup archives unpack
2026-05-22 09:11:24 install libssh-4:amd64 <none> 0.10.5-2+deb12u1
2026-05-22 09:11:25 status half-installed libssh-4:amd64 0.10.5-2+deb12u1
2026-05-22 09:11:26 status unpacked libssh-4:amd64 0.10.5-2+deb12u1
2026-05-22 09:11:30 configure libssh-4:amd64 0.10.5-2+deb12u1 0.10.5-2+deb12u1
"""

_ETC_MACHINE_ID = "8e1cb7a4f3d9421b9a55c2e7d6f0a1b3\n"
_ETC_DEBIAN_VERSION = "12.5\n"

_HOSTNAME_TEMPLATE = "{hostname}\n"

# Marker content for binary files attackers might cat.
_BINARY_GARBAGE = "".join(chr(i % 0x100) for i in range(96, 256))


# ---------------------------------------------------------------------------
# Files: (path) -> (content_template, mode, owner, group)
# ---------------------------------------------------------------------------

_FILES: Final[dict[str, tuple[str, int, str, str]]] = {
    "/etc/passwd": (_ETC_PASSWD, _F644, "root", "root"),
    "/etc/group": (_ETC_GROUP, _F644, "root", "root"),
    "/etc/hostname": (_HOSTNAME_TEMPLATE, _F644, "root", "root"),
    "/etc/issue": (_ETC_ISSUE, _F644, "root", "root"),
    "/etc/os-release": (_ETC_OS_RELEASE, _F644, "root", "root"),
    "/etc/debian_version": (_ETC_DEBIAN_VERSION, _F644, "root", "root"),
    "/etc/machine-id": (_ETC_MACHINE_ID, _F644, "root", "root"),
    "/etc/hosts": (_ETC_HOSTS, _F644, "root", "root"),
    "/etc/resolv.conf": (_ETC_RESOLV_CONF, _F644, "root", "root"),
    "/etc/nsswitch.conf": (_ETC_NSSWITCH, _F644, "root", "root"),
    "/etc/fstab": (_ETC_FSTAB, _F644, "root", "root"),
    "/etc/crontab": (_ETC_CRONTAB, _F644, "root", "root"),
    "/etc/profile": (_ETC_PROFILE, _F644, "root", "root"),
    "/etc/bash.bashrc": (_ETC_BASH_BASHRC, _F644, "root", "root"),
    "/etc/motd": ("", _F644, "root", "root"),
    "/etc/ssh/sshd_config": (_ETC_SSH_SSHD_CONFIG, _F644, "root", "root"),
    "/etc/ssh/ssh_config": (_ETC_SSH_SSH_CONFIG, _F644, "root", "root"),
    "/etc/apt/sources.list": (_ETC_APT_SOURCES, _F644, "root", "root"),
    "/etc/network/interfaces": (_ETC_NETWORK_INTERFACES, _F644, "root", "root"),
    "/proc/version": (_PROC_VERSION, _F644, "root", "root"),
    "/proc/cpuinfo": (_PROC_CPUINFO, _F644, "root", "root"),
    "/proc/meminfo": (_PROC_MEMINFO, _F644, "root", "root"),
    "/proc/mounts": (_PROC_MOUNTS, _F644, "root", "root"),
    "/proc/loadavg": (_PROC_LOADAVG, _F644, "root", "root"),
    "/proc/uptime": (_PROC_UPTIME, _F644, "root", "root"),
    "/proc/self/status": (_PROC_SELF_STATUS, _F644, "root", "root"),
    "/home/{user}/.bashrc": (_HOME_BASHRC, _F644, "{user}", "{user}"),
    "/home/{user}/.profile": (_HOME_PROFILE, _F644, "{user}", "{user}"),
    "/home/{user}/.bash_history": ("", _F600, "{user}", "{user}"),
    "/home/{user}/.ssh/authorized_keys": (
        _HOME_AUTHORIZED_KEYS_TEMPLATE,
        _F600,
        "{user}",
        "{user}",
    ),
    "/home/{user}/.ssh/known_hosts": (_HOME_KNOWN_HOSTS, _F644, "{user}", "{user}"),
    "/root/.bashrc": (_ROOT_BASHRC, _F644, "root", "root"),
    "/root/.bash_history": (_ROOT_BASH_HISTORY, _F600, "root", "root"),
    "/root/.ssh/authorized_keys": (_ROOT_AUTHORIZED_KEYS, _F600, "root", "root"),
    "/root/.ssh/known_hosts": (_HOME_KNOWN_HOSTS, _F644, "root", "root"),
    "/var/log/auth.log": (_VAR_LOG_AUTH, _F640, "root", "adm"),
    "/var/log/syslog": (_VAR_LOG_SYSLOG, _F640, "root", "adm"),
    "/var/log/dpkg.log": (_VAR_LOG_DPKG, _F644, "root", "root"),
    "/var/log/lastlog": (_BINARY_GARBAGE, _F644, "root", "utmp"),
    "/var/log/wtmp": (_BINARY_GARBAGE, _F664, "root", "utmp"),
}

# Permission-denied paths: cat returns the canonical Linux error, no
# bridge call. Even root in the lure persona gets the denial because
# later stages may present a non-root persona for which these are
# genuinely unreadable.
_PERMISSION_DENIED: Final[frozenset[str]] = frozenset(
    {
        "/etc/shadow",
        "/etc/sudoers",
        "/var/log/btmp",
    },
)


# ---------------------------------------------------------------------------
# Directory listings: (path) -> sequence of (name, mode, size, [is_dir])
# ---------------------------------------------------------------------------

_ROOT_DIR_ENTRIES: Final[tuple[FakeEntry, ...]] = (
    FakeEntry("bin", _L777, 7, target="usr/bin", is_symlink=True),
    FakeEntry("boot", _D755, 4096, is_dir=True),
    FakeEntry("dev", _D755, 4096, is_dir=True),
    FakeEntry("etc", _D755, 4096, is_dir=True),
    FakeEntry("home", _D755, 4096, is_dir=True),
    FakeEntry("lib", _L777, 7, target="usr/lib", is_symlink=True),
    FakeEntry("lib64", _L777, 9, target="usr/lib64", is_symlink=True),
    FakeEntry("media", _D755, 4096, is_dir=True),
    FakeEntry("mnt", _D755, 4096, is_dir=True),
    FakeEntry("opt", _D755, 4096, is_dir=True),
    FakeEntry("proc", _D755, 0, is_dir=True),
    FakeEntry("root", _D700, 4096, is_dir=True),
    FakeEntry("run", _D755, 0, is_dir=True),
    FakeEntry("sbin", _L777, 8, target="usr/sbin", is_symlink=True),
    FakeEntry("srv", _D755, 4096, is_dir=True),
    FakeEntry("sys", _D755, 0, is_dir=True),
    FakeEntry("tmp", _D755, 4096, is_dir=True),
    FakeEntry("usr", _D755, 4096, is_dir=True),
    FakeEntry("var", _D755, 4096, is_dir=True),
)

_ETC_DIR_ENTRIES: Final[tuple[FakeEntry, ...]] = (
    FakeEntry("apt", _D755, 4096, is_dir=True),
    FakeEntry("bash.bashrc", _F644, len(_ETC_BASH_BASHRC)),
    FakeEntry("crontab", _F644, len(_ETC_CRONTAB)),
    FakeEntry("cron.d", _D755, 4096, is_dir=True),
    FakeEntry("cron.daily", _D755, 4096, is_dir=True),
    FakeEntry("debian_version", _F644, len(_ETC_DEBIAN_VERSION)),
    FakeEntry("fstab", _F644, len(_ETC_FSTAB)),
    FakeEntry("group", _F644, len(_ETC_GROUP)),
    FakeEntry("hostname", _F644, 14),
    FakeEntry("hosts", _F644, len(_ETC_HOSTS)),
    FakeEntry("init.d", _D755, 4096, is_dir=True),
    FakeEntry("issue", _F644, len(_ETC_ISSUE)),
    FakeEntry("machine-id", _F644, len(_ETC_MACHINE_ID)),
    FakeEntry("motd", _F644, 0),
    FakeEntry("network", _D755, 4096, is_dir=True),
    FakeEntry("nsswitch.conf", _F644, len(_ETC_NSSWITCH)),
    FakeEntry("os-release", _F644, len(_ETC_OS_RELEASE)),
    FakeEntry("passwd", _F644, 0),  # size computed at read time
    FakeEntry("profile", _F644, len(_ETC_PROFILE)),
    FakeEntry("resolv.conf", _F644, len(_ETC_RESOLV_CONF)),
    FakeEntry("shadow", 0o100640, 1437, owner="root", group="shadow"),
    FakeEntry("ssh", _D755, 4096, is_dir=True),
    FakeEntry("sudoers", 0o100440, 755, owner="root", group="root"),
    FakeEntry("sudoers.d", 0o040750, 4096, is_dir=True),
    FakeEntry("systemd", _D755, 4096, is_dir=True),
    FakeEntry("update-motd.d", _D755, 4096, is_dir=True),
)

_VAR_DIR_ENTRIES: Final[tuple[FakeEntry, ...]] = (
    FakeEntry("backups", _D755, 4096, is_dir=True),
    FakeEntry("cache", _D755, 4096, is_dir=True),
    FakeEntry("lib", _D755, 4096, is_dir=True),
    FakeEntry("local", _D755, 4096, is_dir=True),
    FakeEntry("lock", _L777, 9, target="/run/lock", is_symlink=True),
    FakeEntry("log", _D755, 4096, is_dir=True),
    FakeEntry("mail", _L777, 7, target="/var/mail", is_symlink=True),
    FakeEntry("opt", _D755, 4096, is_dir=True),
    FakeEntry("run", _L777, 4, target="/run", is_symlink=True),
    FakeEntry("spool", _D755, 4096, is_dir=True),
    FakeEntry("tmp", _D755, 4096, is_dir=True),
)

_PROC_DIR_ENTRIES: Final[tuple[FakeEntry, ...]] = (
    FakeEntry("1", _D755, 0, is_dir=True),
    FakeEntry("1432", _D755, 0, is_dir=True),
    FakeEntry("cpuinfo", _F444, 0),
    FakeEntry("loadavg", _F444, 0),
    FakeEntry("meminfo", _F444, 0),
    FakeEntry("mounts", _F444, 0),
    FakeEntry("self", _L777, 4, target="1432", is_symlink=True),
    FakeEntry("uptime", _F444, 0),
    FakeEntry("version", _F444, 0),
)

_HOME_DIR_ENTRIES_TEMPLATE: Final[tuple[FakeEntry, ...]] = (
    FakeEntry(".bashrc", _F644, len(_HOME_BASHRC), owner="{user}", group="{user}"),
    FakeEntry(".profile", _F644, len(_HOME_PROFILE), owner="{user}", group="{user}"),
    FakeEntry(".bash_history", _F600, 0, owner="{user}", group="{user}"),
    FakeEntry(".ssh", _D700, 4096, owner="{user}", group="{user}", is_dir=True),
)

_ROOT_HOME_ENTRIES: Final[tuple[FakeEntry, ...]] = (
    FakeEntry(".bashrc", _F644, len(_ROOT_BASHRC)),
    FakeEntry(".bash_history", _F600, len(_ROOT_BASH_HISTORY)),
    FakeEntry(".ssh", _D700, 4096, is_dir=True),
)

_SSH_DIR_ENTRIES: Final[tuple[FakeEntry, ...]] = (
    FakeEntry("authorized_keys", _F600, 0),
    FakeEntry("known_hosts", _F644, len(_HOME_KNOWN_HOSTS)),
)

_VAR_LOG_DIR_ENTRIES: Final[tuple[FakeEntry, ...]] = (
    FakeEntry("auth.log", _F640, len(_VAR_LOG_AUTH), group="adm"),
    FakeEntry("btmp", 0o100600, 0),
    FakeEntry("dpkg.log", _F644, len(_VAR_LOG_DPKG)),
    FakeEntry("lastlog", _F644, len(_BINARY_GARBAGE), group="utmp"),
    FakeEntry("syslog", _F640, len(_VAR_LOG_SYSLOG), group="adm"),
    FakeEntry("wtmp", _F664, len(_BINARY_GARBAGE), group="utmp"),
)


def _format_template(template: str, *, user: str, hostname: str) -> str:
    """Render the {user} and {hostname} placeholders inside a template body.

    Uses ``str.replace`` rather than ``str.format`` so shell-syntax
    braces (``${VAR-default}``, awk programs, JSON in motd) survive
    intact. Only the two literal placeholders we ship are substituted.
    """
    return template.replace("{user}", user).replace("{hostname}", hostname)


def _format_entries(
    entries: tuple[FakeEntry, ...],
    *,
    user: str,
) -> tuple[FakeEntry, ...]:
    """Expand ``{user}`` placeholders in entry names / owners."""
    return tuple(
        FakeEntry(
            name=e.name.replace("{user}", user),
            mode=e.mode,
            size=e.size,
            owner=e.owner.replace("{user}", user),
            group=e.group.replace("{user}", user),
            mtime=e.mtime,
            is_dir=e.is_dir,
            is_symlink=e.is_symlink,
            target=e.target,
        )
        for e in entries
    )


def _resolve_user_path(path: str, *, user: str) -> str:
    """Substitute ``{user}`` into a static path, if present."""
    return path.replace("{user}", user)


def read(path: str, session: LureSessionContext) -> ReadResult:
    """Return the contents of ``path`` from the static filesystem.

    ``status`` distinguishes three cases:

    - ``content``: path is in the table; return the formatted body.
    - ``permission_denied``: path exists conceptually but is unreadable.
      The caller should synthesise the canonical permission-denied
      error in the shell.
    - ``not_in_fakefs``: path is unknown; the caller should route to
      the bridge.
    """
    if path in _PERMISSION_DENIED:
        return ReadResult(status="permission_denied")

    # Template paths keyed under "/home/{user}/..." live in the
    # _FILES dict with the literal placeholder. Look up both raw
    # path and its template-rendered key.
    user = session.username
    hostname = session.hostname

    if path in _FILES:
        template, _mode, _owner, _group = _FILES[path]
        return ReadResult(
            status="content",
            content=_format_template(template, user=user, hostname=hostname),
        )

    # Convert the live path back to a template ("/home/alice/.bashrc"
    # -> "/home/{user}/.bashrc") and try again.
    template_path = path.replace(f"/home/{user}", "/home/{user}")
    if template_path != path and template_path in _FILES:
        template, _mode, _owner, _group = _FILES[template_path]
        return ReadResult(
            status="content",
            content=_format_template(template, user=user, hostname=hostname),
        )

    return ReadResult(status="not_in_fakefs")


def listdir(path: str, session: LureSessionContext) -> ListResult:
    """Return the entries inside ``path`` from the static filesystem."""
    user = session.username
    normalised = path.rstrip("/") or "/"

    if normalised == "/":
        return ListResult(status="entries", entries=_ROOT_DIR_ENTRIES)
    if normalised == "/etc":
        return ListResult(status="entries", entries=_ETC_DIR_ENTRIES)
    if normalised == "/var":
        return ListResult(status="entries", entries=_VAR_DIR_ENTRIES)
    if normalised == "/proc":
        return ListResult(status="entries", entries=_PROC_DIR_ENTRIES)
    if normalised == "/home":
        return ListResult(
            status="entries",
            entries=(FakeEntry(user, _D755, 4096, owner=user, group=user, is_dir=True),),
        )
    if normalised == f"/home/{user}":
        return ListResult(
            status="entries",
            entries=_format_entries(_HOME_DIR_ENTRIES_TEMPLATE, user=user),
        )
    if normalised == "/root":
        return ListResult(status="entries", entries=_ROOT_HOME_ENTRIES)
    if normalised in (f"/home/{user}/.ssh", "/root/.ssh"):
        return ListResult(status="entries", entries=_SSH_DIR_ENTRIES)
    if normalised == "/var/log":
        return ListResult(status="entries", entries=_VAR_LOG_DIR_ENTRIES)

    return ListResult(status="not_in_fakefs")


def system_prompt_summary() -> str:
    """Return a compact summary of the static fs for the bridge prompt.

    The lure passes this to the bridge in every ``submit_command``
    call (via the protocol v2 ``fs_context`` field). The bridge's
    prompt builder includes it in the system prompt so the LLM knows
    which paths are ground truth and which paths it is free to
    invent.

    Kept below 4096 chars to fit ``CommandRequest.fs_context``'s
    pydantic cap.
    """
    return (
        "The following paths on this system have deterministic content "
        "that you must NOT contradict. If asked to cat or ls one of "
        "these, the shell handles it directly; you will not be invoked. "
        "Treat them as ground truth when inventing content for OTHER "
        "paths.\n"
        "\n"
        "Files (cat returns the stored content):\n"
        "- /etc/passwd: users root, daemon, bin, sys, mail, www-data, "
        "nobody, sshd, plus the session user with uid 1000\n"
        "- /etc/group: matching groups for the above\n"
        "- /etc/hostname, /etc/issue, /etc/os-release, /etc/debian_version, "
        "/etc/machine-id: standard Debian 12 (bookworm)\n"
        "- /etc/hosts, /etc/resolv.conf, /etc/nsswitch.conf, /etc/fstab: "
        "standard Debian config\n"
        "- /etc/crontab: standard system entries (run-parts hourly, daily, "
        "weekly, monthly)\n"
        "- /etc/profile, /etc/bash.bashrc, /etc/motd: Debian defaults\n"
        "- /etc/ssh/sshd_config, /etc/ssh/ssh_config: hardened Debian sshd\n"
        "- /etc/apt/sources.list: bookworm main+contrib+non-free-firmware "
        "+ security\n"
        "- /etc/network/interfaces: lo only (systemd-networkd elsewhere)\n"
        "- /proc/version: Debian 6.1.0-18-amd64 kernel\n"
        "- /proc/cpuinfo: 4x Intel Xeon E5-2680 v4 @ 2.40GHz\n"
        "- /proc/meminfo: 8 GiB total, ~6 GiB free\n"
        "- /proc/mounts: vda1 / ext4, plus proc/sys/run/tmp\n"
        "- /proc/loadavg, /proc/uptime: quiet, ~14 days uptime\n"
        "- /home/<user>/.bashrc, /.profile, /.ssh/known_hosts, "
        "/.ssh/authorized_keys: standard\n"
        "- /home/<user>/.bash_history: empty file\n"
        "- /root/.bashrc, /root/.bash_history: standard root shell\n"
        "- /var/log/auth.log, /var/log/syslog, /var/log/dpkg.log: "
        "recent plausible lines\n"
        "\n"
        "Permission-denied paths (any cat returns "
        "'Permission denied'):\n"
        "- /etc/shadow, /etc/sudoers, /var/log/btmp\n"
        "\n"
        "Top-level listings (/, /etc, /var, /proc, /home, /root, "
        "/var/log) return standard Debian content."
    )
