"""Wizard answer and output models.

:class:`WizardAnswers` is the operator-supplied data the wizard needs
in order to produce a working honeypot. It is the single source of
truth that the wizard persists to ``/etc/anglerfish/wizard.json`` so
that ``anglerfish-wizard --reconfigure`` can replay it.

:class:`WizardOutput` records what the wizard *did* — which files were
written, whether secrets were generated — so callers (the systemd
firstboot unit) can take follow-up action and record the run for audit.

Secrets are **never** stored in :class:`WizardAnswers`. They live in
``/etc/anglerfish/anglerfish.env`` (mode 0600) and are regenerated by
the wizard each run. Operators who run ``--reconfigure`` should expect
to restart the bridge and dashboard afterwards because the shared
secret changes.
"""

from __future__ import annotations

from pathlib import Path
from typing import Self

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    HttpUrl,
    IPvAnyAddress,
    model_validator,
)

__all__ = ["NetworkConfig", "WizardAnswers", "WizardOutput"]


class NetworkConfig(BaseModel):
    """Per-NIC IP configuration. DHCP by default; static when ``dhcp=False``."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    dhcp: bool = Field(default=True)
    address: str | None = Field(
        default=None,
        description="Static IPv4 or IPv6 address in CIDR form, e.g. 10.0.0.5/24.",
        max_length=64,
    )
    gateway: IPvAnyAddress | None = Field(default=None)
    dns: tuple[IPvAnyAddress, ...] = Field(default=())

    @model_validator(mode="after")
    def _static_needs_address_and_gateway(self) -> Self:
        if not self.dhcp:
            if self.address is None:
                raise ValueError("static network config requires `address`")
            if self.gateway is None:
                raise ValueError("static network config requires `gateway`")
        return self


class WizardAnswers(BaseModel):
    """Operator-supplied configuration choices (never includes secrets)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    terms_acknowledged: bool = Field(...)
    vm_hostname: str = Field(
        default="anglerfish-honeypot",
        min_length=1,
        max_length=63,
        description="Host operating-system hostname (not the lure's fake hostname).",
    )

    # NIC assignment + per-NIC IP config
    bait_interface: str = Field(..., min_length=1, max_length=32)
    service_interface: str = Field(..., min_length=1, max_length=32)
    bait_network: NetworkConfig = Field(default_factory=NetworkConfig)
    service_network: NetworkConfig = Field(default_factory=NetworkConfig)

    # Operator access
    operator_username: str = Field(
        default="anglerfish-ops",
        min_length=1,
        max_length=32,
    )
    operator_ssh_pubkey: str | None = Field(
        default=None,
        description=(
            "Full authorized_keys-style line for the operator account. "
            "If None, no key is installed and operators must use the noVNC "
            "console (or run --reconfigure later to add one)."
        ),
        max_length=4096,
    )

    # Dashboard authentication
    dashboard_admin_username: str = Field(
        default="admin",
        min_length=1,
        max_length=64,
    )
    dashboard_admin_password_hash: str | None = Field(
        default=None,
        description=(
            "bcrypt-hashed dashboard admin password. Set by the wizard from "
            "the operator's plaintext input. None ⇒ dashboard runs in open "
            "mode (only safe behind a fully-isolated service NIC)."
        ),
        max_length=256,
    )

    # AI inference
    ollama_endpoint: HttpUrl
    ollama_trusted_remote_host: IPvAnyAddress | None = None
    ollama_model: str = Field(default="qwen3:14b", min_length=1, max_length=128)

    # Honeypot persona
    fake_hostname: str = Field(default="srv-prod-01", min_length=1, max_length=63)
    fake_username: str = Field(default="root", min_length=1, max_length=32)

    # Threat-alert webhook (optional). Note: pre-Stage-2 deployments
    # also surfaced Splunk HEC forwarding here; that path was removed
    # alongside the Cowrie integration in 2026-05.
    threat_alert_webhook: HttpUrl | None = None

    # Geo enrichment — MaxMind licence key is optional; without it
    # operators must drop pre-downloaded GeoLite2 .mmdb files in place.
    maxmind_license_key: str | None = Field(
        default=None,
        description=(
            "MaxMind licence key. When supplied, the first-boot oneshot "
            "anglerfish-geo-update.service downloads the GeoLite2-City "
            "and GeoLite2-ASN databases."
        ),
        min_length=8,
        max_length=64,
    )


class WizardOutput(BaseModel):
    """Outcome of a wizard run — file paths and metadata for audit."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    env_path: Path
    nftables_path: Path
    bait_network_path: Path
    service_network_path: Path
    hostname_path: Path
    answers_path: Path
    authorized_keys_path: Path | None = None

    dashboard_session_secret_generated: bool
    credentials_encryption_key_generated: bool
    bridge_shared_secret_generated: bool

    bait_interface: str
    service_interface: str

    preflight_results: tuple[str, ...] = Field(
        default=(),
        description="Human-readable preflight check results (one per service).",
    )
