"""Render the wizard's runtime artefacts.

Five artefacts are produced from a single :class:`WizardAnswers`:

* :func:`render_env` — the ``/etc/anglerfish/anglerfish.env`` file
  consumed by every systemd unit's ``EnvironmentFile`` directive.
* :func:`render_nftables` — the nftables ruleset enforcing the
  bait/service NIC egress split.
* :func:`render_systemd_network` — a per-NIC ``systemd-networkd``
  config file (DHCP or static, per :class:`NetworkConfig`).
* :func:`render_hostname_files` — ``/etc/hostname`` plus the matching
  ``127.0.1.1`` line that ``/etc/hosts`` needs.
* :func:`render_authorized_keys` — the operator account's
  ``~/.ssh/authorized_keys`` body.

All are pure functions: same input → same output, no IO. The wizard
orchestrator calls each, writes the result to disk atomically, and
returns the paths.
"""

from __future__ import annotations

from collections.abc import Iterable

from anglerfish.wizard.answers import NetworkConfig, WizardAnswers
from anglerfish.wizard.sshkey import SshPubKey, parse_ssh_pubkey

__all__ = [
    "render_authorized_keys",
    "render_env",
    "render_hostname_files",
    "render_nftables",
    "render_systemd_network",
]


_HEADER = (
    "# Anglerfish AI runtime configuration.\n"
    "# Generated by the first-boot wizard. Do not edit by hand unless\n"
    "# you understand the security implications of each value.\n"
)

_DEFAULT_DASHBOARD_PORT = 8420
_DEFAULT_BRIDGE_PORT = 8421
# Native SSH lure listener port. Pre-Stage-2 deployments ran Cowrie
# on the same 2222/2223 ports; the lure inherited the default to keep
# attacker-facing surface stable across the Cowrie removal.
_DEFAULT_LURE_PORT = 2222


def render_env(
    answers: WizardAnswers,
    *,
    session_secret: str,
    encryption_key: str,
    bridge_secret: str,
) -> str:
    """Produce the contents of ``/etc/anglerfish/anglerfish.env``."""

    def _line(key: str, value: str | None) -> str | None:
        if value is None:
            return f"# {key}="
        return f"{key}={value}"

    lines: list[str | None] = [
        _HEADER,
        "# --- Global ---------------------------------------------------------------",
        _line("ANGLERFISH_LOG_LEVEL", "INFO"),
        _line("ANGLERFISH_LOG_JSON", "true"),
        _line("ANGLERFISH_DATA_DIR", "/var/lib/anglerfish"),
        "",
        "# --- Network interfaces (consumed by nftables + systemd-networkd) --------",
        _line("ANGLERFISH_BAIT_INTERFACE", answers.bait_interface),
        _line("ANGLERFISH_SERVICE_INTERFACE", answers.service_interface),
        "",
        "# --- Ollama --------------------------------------------------------------",
        _line("ANGLERFISH_OLLAMA__BASE_URL", str(answers.ollama_endpoint)),
        _line(
            "ANGLERFISH_OLLAMA__TRUSTED_REMOTE_HOST",
            str(answers.ollama_trusted_remote_host)
            if answers.ollama_trusted_remote_host is not None
            else None,
        ),
        _line("ANGLERFISH_OLLAMA__MODEL", answers.ollama_model),
        "",
        "# --- Bridge --------------------------------------------------------------",
        _line("ANGLERFISH_BRIDGE__FAKE_HOSTNAME", answers.fake_hostname),
        _line("ANGLERFISH_BRIDGE__FAKE_USERNAME", answers.fake_username),
        _line("ANGLERFISH_BRIDGE__SHARED_SECRET", bridge_secret),
        _line("ANGLERFISH_BRIDGE_URL", f"http://127.0.0.1:{_DEFAULT_BRIDGE_PORT}"),
        "",
        "# --- Lure (native asyncssh SSH honeypot) ---------------------------------",
        # The lure refuses to start unless LISTEN_HOST is a real local
        # interface IP. Static-network setups get the bait IP filled in
        # below; DHCP setups must edit this file once the lease is up
        # to substitute the actual bait NIC address.
        _line("ANGLERFISH_LURE__ENABLED", "true"),
        _line(
            "ANGLERFISH_LURE__LISTEN_HOST",
            _bait_listen_host(answers),
        ),
        _line("ANGLERFISH_LURE__LISTEN_PORT", str(_DEFAULT_LURE_PORT)),
        _line("ANGLERFISH_LURE__HOSTNAME", answers.fake_hostname),
        _line("ANGLERFISH_LURE__HOST_KEY_DIR", "/var/lib/anglerfish/lure-keys"),
        "",
        "# --- Dashboard -----------------------------------------------------------",
        # Bind to all interfaces; nftables permits dashboard ingress on the
        # service NIC only. See render_nftables().
        _line("ANGLERFISH_DASHBOARD__HOST", "0.0.0.0"),  # noqa: S104  # nosec B104
        _line("ANGLERFISH_DASHBOARD__PORT", str(_DEFAULT_DASHBOARD_PORT)),
        _line("ANGLERFISH_DASHBOARD__SESSION_SECRET", session_secret),
        _line("ANGLERFISH_DASHBOARD__ADMIN_USERNAME", answers.dashboard_admin_username),
        _line(
            "ANGLERFISH_DASHBOARD__ADMIN_PASSWORD_HASH",
            answers.dashboard_admin_password_hash,
        ),
        "",
        "# --- Threat alerting -----------------------------------------------------",
        _line(
            "ANGLERFISH_THREAT__ALERT_WEBHOOK_URL",
            str(answers.threat_alert_webhook) if answers.threat_alert_webhook is not None else None,
        ),
        "",
        "# --- Credentials ---------------------------------------------------------",
        _line("ANGLERFISH_CREDENTIALS__ENCRYPTION_KEY", encryption_key),
        "",
        "# --- Session store (Stage 4 persistent SQLite) ---------------------------",
        # database_path defaults to /var/lib/anglerfish/sessions.db. Uncomment
        # to relocate (e.g. onto a larger volume). max_active_sessions_returned
        # caps the /api/sessions response size; raise if the dashboard's
        # active-sessions view is being truncated.
        _line("# ANGLERFISH_SESSIONS__DATABASE_PATH", "/var/lib/anglerfish/sessions.db"),
        _line("# ANGLERFISH_SESSIONS__MAX_ACTIVE_SESSIONS_RETURNED", "500"),
        "",
        "# --- Audit log (Stage 4.2: writer + tailer share this path) --------------",
        # log_path is read by every AuditLog construction site (bridge,
        # lure, dashboard, CLI) AND by the Stage 4.2 AuditTailer that
        # populates the session store. Relocate carefully: logrotate
        # must continue to copytruncate this exact file, and the chattr
        # +a invariant must be re-applied if it moves between
        # filesystems.
        _line("# ANGLERFISH_AUDIT__LOG_PATH", "/var/log/anglerfish/audit.jsonl"),
        "",
        "# --- Geo enrichment (MaxMind GeoLite2) -----------------------------------",
        _line("ANGLERFISH_GEO__CITY_DB_PATH", "/var/lib/anglerfish/geo/GeoLite2-City.mmdb"),
        _line("ANGLERFISH_GEO__ASN_DB_PATH", "/var/lib/anglerfish/geo/GeoLite2-ASN.mmdb"),
        _line("ANGLERFISH_GEO__MAXMIND_LICENSE_KEY", answers.maxmind_license_key),
        "",
    ]
    return "\n".join(_iter_lines(lines))


def _bait_listen_host(answers: WizardAnswers) -> str | None:
    """Best-effort bait-NIC IP for ``ANGLERFISH_LURE__LISTEN_HOST``.

    Returns the literal IP string for static configs, ``None`` for
    DHCP setups (the env-file line stays commented; operators fill in
    the lease IP once the bait NIC is up).
    """
    net = answers.bait_network
    if net.dhcp or not net.address:
        return None
    # NetworkConfig.address is stored as ``ip/prefix``; strip the suffix.
    head = net.address.split("/", 1)[0].strip()
    return head or None


def render_nftables(
    answers: WizardAnswers,
    *,
    dashboard_port: int = _DEFAULT_DASHBOARD_PORT,
    lure_listen_port: int = _DEFAULT_LURE_PORT,
) -> str:
    """Render the nftables ruleset for the bait/service NIC split.

    The ruleset enforces three invariants:

    1. The native SSH lure listens on the bait NIC at
       ``lure_listen_port`` and nothing else attacker-facing is open.
    2. Egress from the bait NIC is dropped entirely (only DNS is
       permitted, so the LLM's plausible-shell responses can still
       reference DNS-resolvable hostnames in passing).
    3. Egress from the service NIC is restricted to Ollama (11434),
       the dashboard's own port, DNS, NTP.
    """
    bait = _quote_iface(answers.bait_interface)
    service = _quote_iface(answers.service_interface)

    return f"""#!/usr/sbin/nft -f
# Generated by anglerfish-wizard. Do not edit by hand;
# re-run `anglerfish-wizard --reconfigure` to regenerate.

flush ruleset

table inet anglerfish {{
    chain input {{
        type filter hook input priority filter; policy drop;

        ct state established,related accept
        iifname "lo" accept

        # Bait NIC: native SSH lure listener.
        iifname {bait} tcp dport {lure_listen_port} accept

        # Dashboard + ops SSH on the service NIC.
        iifname {service} tcp dport {dashboard_port} accept
        iifname {service} tcp dport 22 accept

        # ICMP for diagnostics.
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept
    }}

    chain forward {{
        type filter hook forward priority filter; policy drop;
    }}

    chain output {{
        type filter hook output priority filter; policy drop;

        oifname "lo" accept
        ct state established,related accept

        # Bait egress: DNS only. A compromised honeypot cannot phone home.
        oifname {bait} udp dport 53 accept
        oifname {bait} drop

        # Service egress: Ollama and the dashboard's own port. DNS+NTP
        # outbound for system upkeep.
        oifname {service} tcp dport 11434 accept
        oifname {service} tcp dport {dashboard_port} accept
        oifname {service} udp dport {{ 53, 123 }} accept
    }}
}}
"""


def render_systemd_network(interface: str, config: NetworkConfig) -> str:
    """Render a single ``systemd-networkd`` ``.network`` file."""
    _validate_iface(interface)
    lines: list[str] = [
        "# Generated by anglerfish-wizard.",
        "# Do not edit by hand — re-run `anglerfish-wizard --reconfigure`.",
        "",
        "[Match]",
        f"Name={interface}",
        "",
        "[Network]",
    ]
    if config.dhcp:
        lines.append("DHCP=yes")
    else:
        # _static_needs_address_and_gateway in NetworkConfig guarantees
        # these fields are present when dhcp=False — the explicit raise
        # below is unreachable in practice but keeps mypy strict happy
        # without an assert (which ruff S101 flags in src/).
        if config.address is None or config.gateway is None:
            raise ValueError("static network config missing address or gateway")
        lines.append(f"Address={config.address}")
        lines.append(f"Gateway={config.gateway}")
        lines.extend(f"DNS={dns}" for dns in config.dns)
    lines.append("")
    return "\n".join(lines)


def render_hostname_files(hostname: str) -> tuple[str, str]:
    """Render ``(etc_hostname_body, etc_hosts_body)`` for the VM hostname.

    The ``/etc/hostname`` file is just the hostname plus a trailing
    newline. The ``/etc/hosts`` body is a minimal, deterministic file
    with loopback entries plus the VM's own name.
    """
    if not hostname:
        raise ValueError("hostname cannot be empty")
    if len(hostname) > 63:
        raise ValueError(f"hostname too long: {hostname!r}")
    for ch in hostname:
        if not (ch.isalnum() or ch in "-."):
            raise ValueError(f"invalid character in hostname: {hostname!r}")
    etc_hostname = hostname + "\n"
    etc_hosts = (
        "# Generated by anglerfish-wizard.\n"
        "127.0.0.1\tlocalhost\n"
        f"127.0.1.1\t{hostname}\n"
        "\n"
        "::1     ip6-localhost ip6-loopback\n"
        "fe00::0 ip6-localnet\n"
        "ff00::0 ip6-mcastprefix\n"
        "ff02::1 ip6-allnodes\n"
        "ff02::2 ip6-allrouters\n"
    )
    return etc_hostname, etc_hosts


def render_authorized_keys(raw_key: str) -> str:
    """Validate + canonicalise an ``authorized_keys`` body.

    Wraps :func:`anglerfish.wizard.sshkey.parse_ssh_pubkey`. The body
    contains exactly one canonical key line plus a trailing newline —
    the wizard explicitly does not support multi-key files; operators
    needing extra keys can edit the file by hand after install.
    """
    parsed: SshPubKey = parse_ssh_pubkey(raw_key)
    return parsed.to_authorized_keys_line() + "\n"


def _quote_iface(name: str) -> str:
    """Quote an interface name for safe inclusion in an nftables rule."""
    _validate_iface(name)
    return f'"{name}"'


def _validate_iface(name: str) -> None:
    if not name:
        raise ValueError("interface name cannot be empty")
    if len(name) > 32:
        raise ValueError(f"interface name too long: {name!r}")
    for ch in name:
        if not (ch.isalnum() or ch in "-_."):
            raise ValueError(f"invalid character in interface name: {name!r}")


def _iter_lines(parts: Iterable[str | None]) -> Iterable[str]:
    for p in parts:
        if p is None:
            continue
        yield p
