"""Render the wizard's runtime artefacts.

Six artefacts are produced from a single :class:`WizardAnswers`:

* :func:`render_env` — the ``/etc/anglerfish/anglerfish.env`` file
  consumed by every systemd unit's ``EnvironmentFile`` directive.
* :func:`render_nftables` — the nftables ruleset enforcing the
  bait/service NIC egress split.
* :func:`render_cowrie_cfg` — Cowrie's ``cowrie.cfg`` with the
  Anglerfish output plugin enabled and the listener ports / hostname
  baked in.
* :func:`render_systemd_network` — a per-NIC ``systemd-networkd``
  config file (DHCP or static, per :class:`NetworkConfig`).
* :func:`render_hostname_files` — ``/etc/hostname`` plus the matching
  ``127.0.1.1`` line that ``/etc/hosts`` needs.
* :func:`render_authorized_keys` — the operator account's
  ``~/.ssh/authorized_keys`` body.

All are pure functions: same input → same output, no IO. The wizard
orchestrator calls each, writes the result to disk atomically, and
returns the paths.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path

from anglerfish.wizard.answers import NetworkConfig, WizardAnswers
from anglerfish.wizard.sshkey import SshPubKey, parse_ssh_pubkey

__all__ = [
    "render_authorized_keys",
    "render_cowrie_cfg",
    "render_env",
    "render_hostname_files",
    "render_nftables",
    "render_systemd_network",
]


_HEADER = (
    "# Anglerfish AI runtime configuration.\n"
    "# Generated by the first-boot wizard. Do not edit by hand unless\n"
    "# you understand the security implications of each value.\n"
)

_DEFAULT_DASHBOARD_PORT = 8420
_DEFAULT_BRIDGE_PORT = 8421
_DEFAULT_SSH_PORT = 2222
_DEFAULT_TELNET_PORT = 2223
# Lure listener port. Same as Cowrie's 2222 by default so a single
# bait-NIC nftables rule covers both during the Cowrie deprecation
# window. Operators that want the lure on a distinct port set
# ANGLERFISH_LURE__LISTEN_PORT in the env file and re-run the wizard.
_DEFAULT_LURE_PORT = 2222


def render_env(
    answers: WizardAnswers,
    *,
    session_secret: str,
    encryption_key: str,
    bridge_secret: str,
) -> str:
    """Produce the contents of ``/etc/anglerfish/anglerfish.env``."""

    def _line(key: str, value: str | None) -> str | None:
        if value is None:
            return f"# {key}="
        return f"{key}={value}"

    lines: list[str | None] = [
        _HEADER,
        "# --- Global ---------------------------------------------------------------",
        _line("ANGLERFISH_LOG_LEVEL", "INFO"),
        _line("ANGLERFISH_LOG_JSON", "true"),
        _line("ANGLERFISH_DATA_DIR", "/var/lib/anglerfish"),
        "",
        "# --- Network interfaces (consumed by nftables + systemd-networkd) --------",
        _line("ANGLERFISH_BAIT_INTERFACE", answers.bait_interface),
        _line("ANGLERFISH_SERVICE_INTERFACE", answers.service_interface),
        "",
        "# --- Ollama --------------------------------------------------------------",
        _line("ANGLERFISH_OLLAMA__BASE_URL", str(answers.ollama_endpoint)),
        _line(
            "ANGLERFISH_OLLAMA__TRUSTED_REMOTE_HOST",
            str(answers.ollama_trusted_remote_host)
            if answers.ollama_trusted_remote_host is not None
            else None,
        ),
        _line("ANGLERFISH_OLLAMA__MODEL", answers.ollama_model),
        "",
        "# --- Bridge --------------------------------------------------------------",
        _line("ANGLERFISH_BRIDGE__FAKE_HOSTNAME", answers.fake_hostname),
        _line("ANGLERFISH_BRIDGE__FAKE_USERNAME", answers.fake_username),
        _line("ANGLERFISH_BRIDGE__SHARED_SECRET", bridge_secret),
        _line("ANGLERFISH_BRIDGE_URL", f"http://127.0.0.1:{_DEFAULT_BRIDGE_PORT}"),
        "",
        "# --- Cowrie (deprecated, retained for transition window) -----------------",
        # Stage 2 replaces Cowrie with the native asyncssh lure. The
        # Cowrie keys stay until a later commit deletes the integration,
        # so operators upgrading in place can run both for an A/B
        # window. New installs leave the Cowrie listener disabled (set
        # ANGLERFISH_COWRIE__SSH_LISTEN_PORT to 0 if you want to be
        # explicit) and rely on the lure.
        _line("ANGLERFISH_COWRIE__HOSTNAME", answers.fake_hostname),
        _line("ANGLERFISH_COWRIE__SSH_LISTEN_PORT", str(_DEFAULT_SSH_PORT)),
        _line("ANGLERFISH_COWRIE__TELNET_LISTEN_PORT", str(_DEFAULT_TELNET_PORT)),
        "",
        "# --- Lure (native asyncssh SSH honeypot, replaces Cowrie) ----------------",
        # The lure refuses to start unless LISTEN_HOST is a real local
        # interface IP. Static-network setups get the bait IP filled in
        # below; DHCP setups must edit this file once the lease is up
        # to substitute the actual bait NIC address.
        _line("ANGLERFISH_LURE__ENABLED", "true"),
        _line(
            "ANGLERFISH_LURE__LISTEN_HOST",
            _bait_listen_host(answers),
        ),
        _line("ANGLERFISH_LURE__LISTEN_PORT", str(_DEFAULT_LURE_PORT)),
        _line("ANGLERFISH_LURE__HOSTNAME", answers.fake_hostname),
        _line("ANGLERFISH_LURE__HOST_KEY_DIR", "/var/lib/anglerfish/lure-keys"),
        "",
        "# --- Dashboard -----------------------------------------------------------",
        # Bind to all interfaces; nftables permits dashboard ingress on the
        # service NIC only. See render_nftables().
        _line("ANGLERFISH_DASHBOARD__HOST", "0.0.0.0"),  # noqa: S104  # nosec B104
        _line("ANGLERFISH_DASHBOARD__PORT", str(_DEFAULT_DASHBOARD_PORT)),
        _line("ANGLERFISH_DASHBOARD__SESSION_SECRET", session_secret),
        _line("ANGLERFISH_DASHBOARD__ADMIN_USERNAME", answers.dashboard_admin_username),
        _line(
            "ANGLERFISH_DASHBOARD__ADMIN_PASSWORD_HASH",
            answers.dashboard_admin_password_hash,
        ),
        "",
        "# --- Splunk HEC ----------------------------------------------------------",
        _line("ANGLERFISH_SPLUNK__ENABLED", "true" if answers.splunk_enabled else "false"),
        _line(
            "ANGLERFISH_SPLUNK__HEC_URL",
            str(answers.splunk_hec_url) if answers.splunk_hec_url is not None else None,
        ),
        _line("ANGLERFISH_SPLUNK__HEC_TOKEN", answers.splunk_hec_token),
        "",
        "# --- Threat alerting -----------------------------------------------------",
        _line(
            "ANGLERFISH_THREAT__ALERT_WEBHOOK_URL",
            str(answers.threat_alert_webhook) if answers.threat_alert_webhook is not None else None,
        ),
        "",
        "# --- Credentials ---------------------------------------------------------",
        _line("ANGLERFISH_CREDENTIALS__ENCRYPTION_KEY", encryption_key),
        "",
        "# --- Session store (Stage 4 persistent SQLite) ---------------------------",
        # database_path defaults to /var/lib/anglerfish/sessions.db. Uncomment
        # to relocate (e.g. onto a larger volume). max_active_sessions_returned
        # caps the /api/sessions response size; raise if the dashboard's
        # active-sessions view is being truncated.
        _line("# ANGLERFISH_SESSIONS__DATABASE_PATH", "/var/lib/anglerfish/sessions.db"),
        _line("# ANGLERFISH_SESSIONS__MAX_ACTIVE_SESSIONS_RETURNED", "500"),
        "",
        "# --- Audit log (Stage 4.2: writer + tailer share this path) --------------",
        # log_path is read by every AuditLog construction site (bridge,
        # lure, dashboard, CLI) AND by the Stage 4.2 AuditTailer that
        # populates the session store. Relocate carefully: logrotate
        # must continue to copytruncate this exact file, and the chattr
        # +a invariant must be re-applied if it moves between
        # filesystems.
        _line("# ANGLERFISH_AUDIT__LOG_PATH", "/var/log/anglerfish/audit.jsonl"),
        "",
        "# --- Geo enrichment (MaxMind GeoLite2) -----------------------------------",
        _line("ANGLERFISH_GEO__CITY_DB_PATH", "/var/lib/anglerfish/geo/GeoLite2-City.mmdb"),
        _line("ANGLERFISH_GEO__ASN_DB_PATH", "/var/lib/anglerfish/geo/GeoLite2-ASN.mmdb"),
        _line("ANGLERFISH_GEO__MAXMIND_LICENSE_KEY", answers.maxmind_license_key),
        "",
    ]
    return "\n".join(_iter_lines(lines))


def _bait_listen_host(answers: WizardAnswers) -> str | None:
    """Best-effort bait-NIC IP for ``ANGLERFISH_LURE__LISTEN_HOST``.

    Returns the literal IP string for static configs, ``None`` for
    DHCP setups (the env-file line stays commented; operators fill in
    the lease IP once the bait NIC is up).
    """
    net = answers.bait_network
    if net.dhcp or not net.address:
        return None
    # NetworkConfig.address is stored as ``ip/prefix``; strip the suffix.
    head = net.address.split("/", 1)[0].strip()
    return head or None


def render_nftables(
    answers: WizardAnswers,
    *,
    dashboard_port: int = _DEFAULT_DASHBOARD_PORT,
    ssh_listen_port: int = _DEFAULT_SSH_PORT,
    telnet_listen_port: int = _DEFAULT_TELNET_PORT,
    lure_listen_port: int = _DEFAULT_LURE_PORT,
) -> str:
    """Render the nftables ruleset for the bait/service NIC split.

    The ruleset enforces three invariants:

    1. The lure SSH listener (Stage 2 replacement for Cowrie) is the
       primary port open on the bait NIC. Cowrie's legacy SSH + Telnet
       ports stay accepted through the deprecation window so operators
       can run both during A/B; a later commit removes those rules
       when Cowrie itself is deleted.
    2. Egress from the bait NIC is dropped entirely (only DNS is
       permitted, so the LLM's plausible-shell responses can still
       reference DNS-resolvable hostnames in passing).
    3. Egress from the service NIC is restricted to Ollama (11434),
       Splunk HEC (8088), the dashboard's own port, DNS, NTP.
    """
    bait = _quote_iface(answers.bait_interface)
    service = _quote_iface(answers.service_interface)

    # Build the bait-NIC accept rule. If the lure port matches Cowrie's
    # SSH port (the default-aligned case), one rule covers both. If
    # the operator picked a distinct lure port, emit a separate rule.
    cowrie_ports = {ssh_listen_port, telnet_listen_port}
    if lure_listen_port in cowrie_ports:
        bait_accept = (
            f"iifname {bait} tcp dport {{ {ssh_listen_port}, {telnet_listen_port} }} accept"
        )
    else:
        bait_accept = (
            f"iifname {bait} tcp dport {lure_listen_port} accept  "
            "# native lure (Stage 2)\n        "
            f"iifname {bait} tcp dport "
            f"{{ {ssh_listen_port}, {telnet_listen_port} }} accept  "
            "# Cowrie (deprecation window)"
        )

    return f"""#!/usr/sbin/nft -f
# Generated by anglerfish-wizard. Do not edit by hand;
# re-run `anglerfish-wizard --reconfigure` to regenerate.

flush ruleset

table inet anglerfish {{
    chain input {{
        type filter hook input priority filter; policy drop;

        ct state established,related accept
        iifname "lo" accept

        # Bait NIC: lure (Stage 2) and Cowrie (legacy, transition window).
        {bait_accept}

        # Dashboard + ops SSH on the service NIC.
        iifname {service} tcp dport {dashboard_port} accept
        iifname {service} tcp dport 22 accept

        # ICMP for diagnostics.
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept
    }}

    chain forward {{
        type filter hook forward priority filter; policy drop;
    }}

    chain output {{
        type filter hook output priority filter; policy drop;

        oifname "lo" accept
        ct state established,related accept

        # Bait egress: DNS only. A compromised honeypot cannot phone home.
        oifname {bait} udp dport 53 accept
        oifname {bait} drop

        # Service egress: only Ollama, Splunk HEC, and our own dashboard port.
        oifname {service} tcp dport 11434 accept
        oifname {service} tcp dport 8088 accept
        oifname {service} tcp dport {dashboard_port} accept
        oifname {service} udp dport {{ 53, 123 }} accept
    }}
}}
"""


def render_cowrie_cfg(
    answers: WizardAnswers,
    *,
    ssh_listen_port: int = _DEFAULT_SSH_PORT,
    telnet_listen_port: int = _DEFAULT_TELNET_PORT,
    log_path: Path = Path("/var/log/cowrie/cowrie.json"),
) -> str:
    """Render Cowrie's main configuration file.

    Enables the Anglerfish output plugin and bakes in the wizard's
    hostname + listener-port choices. Anything else uses Cowrie's
    upstream defaults.
    """
    return f"""# Cowrie configuration generated by anglerfish-wizard.
# Re-run `anglerfish-wizard --reconfigure` to regenerate.

[honeypot]
hostname = {answers.fake_hostname}
log_path = /var/log/cowrie
download_path = /var/lib/anglerfish/downloads
data_path = /opt/cowrie/data

ssh_version_string = SSH-2.0-OpenSSH_8.9p1 Debian-1ubuntu1
banner_file =

auth_class = AuthRandom
auth_class_parameters = 2, 5, 10

[ssh]
enabled = true
listen_endpoints = tcp:{ssh_listen_port}:interface=0.0.0.0
sftp_enabled = false
forwarding = false
forward_redirect = false
forward_tunnel = false

[telnet]
enabled = true
listen_endpoints = tcp:{telnet_listen_port}:interface=0.0.0.0

[output_anglerfish]
enabled = true

[output_jsonlog]
enabled = true
logfile = {log_path}
epoch_timestamp = false

[shell]
filesystem = share/cowrie/fs.pickle
processes = share/cowrie/cmdoutput.json
"""


def render_systemd_network(interface: str, config: NetworkConfig) -> str:
    """Render a single ``systemd-networkd`` ``.network`` file."""
    _validate_iface(interface)
    lines: list[str] = [
        "# Generated by anglerfish-wizard.",
        "# Do not edit by hand — re-run `anglerfish-wizard --reconfigure`.",
        "",
        "[Match]",
        f"Name={interface}",
        "",
        "[Network]",
    ]
    if config.dhcp:
        lines.append("DHCP=yes")
    else:
        # _static_needs_address_and_gateway in NetworkConfig guarantees
        # these fields are present when dhcp=False — the explicit raise
        # below is unreachable in practice but keeps mypy strict happy
        # without an assert (which ruff S101 flags in src/).
        if config.address is None or config.gateway is None:
            raise ValueError("static network config missing address or gateway")
        lines.append(f"Address={config.address}")
        lines.append(f"Gateway={config.gateway}")
        lines.extend(f"DNS={dns}" for dns in config.dns)
    lines.append("")
    return "\n".join(lines)


def render_hostname_files(hostname: str) -> tuple[str, str]:
    """Render ``(etc_hostname_body, etc_hosts_body)`` for the VM hostname.

    The ``/etc/hostname`` file is just the hostname plus a trailing
    newline. The ``/etc/hosts`` body is a minimal, deterministic file
    with loopback entries plus the VM's own name.
    """
    if not hostname:
        raise ValueError("hostname cannot be empty")
    if len(hostname) > 63:
        raise ValueError(f"hostname too long: {hostname!r}")
    for ch in hostname:
        if not (ch.isalnum() or ch in "-."):
            raise ValueError(f"invalid character in hostname: {hostname!r}")
    etc_hostname = hostname + "\n"
    etc_hosts = (
        "# Generated by anglerfish-wizard.\n"
        "127.0.0.1\tlocalhost\n"
        f"127.0.1.1\t{hostname}\n"
        "\n"
        "::1     ip6-localhost ip6-loopback\n"
        "fe00::0 ip6-localnet\n"
        "ff00::0 ip6-mcastprefix\n"
        "ff02::1 ip6-allnodes\n"
        "ff02::2 ip6-allrouters\n"
    )
    return etc_hostname, etc_hosts


def render_authorized_keys(raw_key: str) -> str:
    """Validate + canonicalise an ``authorized_keys`` body.

    Wraps :func:`anglerfish.wizard.sshkey.parse_ssh_pubkey`. The body
    contains exactly one canonical key line plus a trailing newline —
    the wizard explicitly does not support multi-key files; operators
    needing extra keys can edit the file by hand after install.
    """
    parsed: SshPubKey = parse_ssh_pubkey(raw_key)
    return parsed.to_authorized_keys_line() + "\n"


def _quote_iface(name: str) -> str:
    """Quote an interface name for safe inclusion in an nftables rule."""
    _validate_iface(name)
    return f'"{name}"'


def _validate_iface(name: str) -> None:
    if not name:
        raise ValueError("interface name cannot be empty")
    if len(name) > 32:
        raise ValueError(f"interface name too long: {name!r}")
    for ch in name:
        if not (ch.isalnum() or ch in "-_."):
            raise ValueError(f"invalid character in interface name: {name!r}")


def _iter_lines(parts: Iterable[str | None]) -> Iterable[str]:
    for p in parts:
        if p is None:
            continue
        yield p
